// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using gs.Data;

#nullable disable

namespace gs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gs.Models.AbrigoOcupacao", b =>
                {
                    b.Property<long>("IdOcupacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdOcupacao"));

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_registro");

                    b.Property<long>("FkIdAbrigo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("fk_id_abrigo");

                    b.Property<int>("NumeroPessoa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_pessoa");

                    b.HasKey("IdOcupacao");

                    b.HasIndex("FkIdAbrigo");

                    b.ToTable("T_SAFEHUB_ABRIGO_OCUPACAO");
                });

            modelBuilder.Entity("gs.Models.CadastroAbrigo", b =>
                {
                    b.Property<long>("IdCadastroAbrigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCadastroAbrigo"));

                    b.Property<int>("CapacidadePessoa")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("capacidade_pessoa");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("latitude");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("longitude");

                    b.Property<string>("NomeAbrigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome_abrigo");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_responsavel");

                    b.HasKey("IdCadastroAbrigo");

                    b.ToTable("T_SAFEHUB_CADASTRO_ABRIGO");
                });

            modelBuilder.Entity("gs.Models.CadastroUsuario", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("email");

                    b.Property<long>("FkIdAbrigo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("fk_id_abrigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("FkIdAbrigo");

                    b.ToTable("T_SAFEHUB_CADASTRO_USUARIO");
                });

            modelBuilder.Entity("gs.Models.EstoqueAbrigo", b =>
                {
                    b.Property<long>("IdEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEstoque"));

                    b.Property<long>("FkIdAbrigo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("fk_id_abrigo");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_item");

                    b.Property<float>("Quantidade")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("quantidade");

                    b.Property<int>("TipoItem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("tp_item");

                    b.HasKey("IdEstoque");

                    b.HasIndex("FkIdAbrigo");

                    b.ToTable("T_SAFEHUB_ESTOQUE_ABRIGO");
                });

            modelBuilder.Entity("gs.Models.AbrigoOcupacao", b =>
                {
                    b.HasOne("gs.Models.CadastroAbrigo", "ChaveAbrigo")
                        .WithMany("Ocupacoes")
                        .HasForeignKey("FkIdAbrigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ocupacao_Abrigo");

                    b.Navigation("ChaveAbrigo");
                });

            modelBuilder.Entity("gs.Models.CadastroUsuario", b =>
                {
                    b.HasOne("gs.Models.CadastroAbrigo", "ChaveAbrigo")
                        .WithMany("Usuarios")
                        .HasForeignKey("FkIdAbrigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Abrigo");

                    b.Navigation("ChaveAbrigo");
                });

            modelBuilder.Entity("gs.Models.EstoqueAbrigo", b =>
                {
                    b.HasOne("gs.Models.CadastroAbrigo", "ChaveAbrigo")
                        .WithMany("Estoques")
                        .HasForeignKey("FkIdAbrigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Estoque_Abrigo");

                    b.Navigation("ChaveAbrigo");
                });

            modelBuilder.Entity("gs.Models.CadastroAbrigo", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("Ocupacoes");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
